
///
/// @file random.h Pseudorandom number generation.
///

#ifndef THEORETICA_PSEUDORANDOM_H
#define THEORETICA_PSEUDORANDOM_H

#include <vector>
#include "../core/error.h"


namespace theoretica {
namespace random {


    /// @class BasePrng
	/// Base class for pseudorandom number generators,
	/// following the UniformRandomBitGenerator C++ concept.
	///
    /// @tparam UIntType Type of the generated pseudorandom numbers (generally uint64_t) 
    template <typename UIntType>
    struct BasePrng {

		/// The type of the generated pseudorandom numbers.
        using result_type = UIntType;

		/// The minimum possible value generated by the generator.
        static constexpr result_type min() { 
            return std::numeric_limits<result_type>::min(); 
        }
        
		/// The maximum possible value generated by the generator.
        static constexpr result_type max() { 
            return std::numeric_limits<result_type>::max(); 
        }
    };


	/// @class SplitmixPrng
	/// SplitMix64 pseudorandom number generator,
	/// satisfying the UniformRandomBitGenerator concept.
    struct SplitmixPrng : public BasePrng<uint64_t> {

		// Internal state of the generator
        uint64_t state;

        constexpr explicit SplitmixPrng(uint64_t seed = 0) : state(seed) {}

        // In C++14, constexpr functions are allowed to mutate member state
        constexpr result_type operator()() {

			// Recurrent state
            state += 0x9e3779b97f4a7c15;
            
            // Hash the output
            uint64_t res = state;
            res = (res ^ (res >> 30)) * 0xbf58476d1ce4e5b9;
            res = (res ^ (res >> 27)) * 0x94d049bb133111eb;
            return res ^ (res >> 31);
        }
    };


	/// @class XoshiroPrng
    /// Xoshiro256++ pseudorandom number generator implementation,
	/// satisfying the UniformRandomBitGenerator concept.
    struct XoshiroPrng : public BasePrng<uint64_t> {

		// Internal state of the generator
        uint64_t state[4];


		/// Construct a Xoshiro256++ generator with the given seed.
        constexpr explicit XoshiroPrng(uint64_t seed = 0) : state() {

            // Use SplitmixPrng to prevent zero-state and thoroughly mix the seed
            SplitmixPrng splitmix (seed);
            state[0] = splitmix();
            state[1] = splitmix();
            state[2] = splitmix();
            state[3] = splitmix();
        }


		/// Construct a Xoshiro256++ generator with the given state.
		constexpr explicit XoshiroPrng(const std::array<uint64_t, 4>& s) : state() {
			state[0] = s[0];
			state[1] = s[1];
			state[2] = s[2];
			state[3] = s[3];
		}


		/// Generate a pseudorandom number using the Xoshiro256++ algorithm.
        constexpr result_type operator()() {
			
            const uint64_t result = bits::rotate(state[0] + state[3], 23) + state[0];
            const uint64_t temp = state[1] << 17;

            state[2] ^= state[0];
            state[3] ^= state[1];
            state[1] ^= state[2];
            state[0] ^= state[3];

            state[2] ^= temp;
            state[3] = bits::rotate(state[3], 45);

            return result;
        }


		/// Jump ahead 2^128 steps in the sequence, equivalent to 2^128 calls to operator().
		constexpr void jump() {

			uint64_t s[4] = {0, 0, 0, 0};
			constexpr uint64_t JUMP[] = {
				0x180ec6d33cfd0aba,
				0xd5a61266f0c9392c,
				0xa9582618e03fc9aa,
				0x39abdc4529b1661c
			};
			
			for (int i = 0; i < 4; i++) {
				for (int b = 0; b < 64; b++) {

					if (JUMP[i] & (uint64_t(1) << b)) {
						s[0] ^= state[0];
						s[1] ^= state[1];
						s[2] ^= state[2];
						s[3] ^= state[3];
					}

					operator()();
				}
			}

			state[0] = s[0];
			state[1] = s[1];
			state[2] = s[2];
			state[3] = s[3];
		}

    };


	/// @class WyrandPrng
	/// Wyrand pseudorandom number generator implementation,
	/// satisfying the UniformRandomBitGenerator concept.
	struct WyrandPrng : public BasePrng<uint64_t> {

		// Seed of the generator
		uint64_t seed;

		// Parameters of the generator
		uint64_t p1, p2;


		/// Construct a Wyrand generator with the given seed and parameters.
		///
		/// @param seed The seed of the generator
		/// @param p1 The additive parameter
		/// @param p2 The XOR parameter
		constexpr explicit WyrandPrng(uint64_t seed = 0, uint64_t p1 = 2549536629329, uint64_t p2 = 136137137) 
			: seed(seed), p1(p1), p2(p2) {}

		constexpr result_type operator()() {
			seed += p1;
			return bits::mix_mum(seed ^ p2, seed);
		}
	};


	/// Shuffle a set by exchanging random couples of elements.
	/// 
	/// @param v The set to shuffle (as a Vector with [] and .size() methods)
	/// @param g An already initialized PRNG
	/// @param rounds The number of pairs to exchange.
	/// @return A reference to the shuffled vector
	template<typename Vector, typename PRNG>
	inline Vector& shuffle(Vector& v, PRNG& g, unsigned int rounds) {

		if(v.size() == 0)
			TH_MATH_ERROR("shuffle", v.size(), MathError::InvalidArgument);

		for (unsigned int i = 0; i < rounds; ++i) {
			
			// Generate two random indices
			const size_t index1 = g() % v.size();
			const size_t index2 = g() % v.size();

			// Exchange the two values at the random indices
			std::swap(v[index1], v[index2]);
		}

		return v;
	}


	/// Shuffle a set by exchanging random couples of elements.
	/// The number of rounds used is \f$(N - 1)^2\f$.
	/// 
	/// @param v The set to shuffle (as a Vector with [] and .size() methods)
	/// @param g An already initialized PRNG
	/// @return A reference to the shuffled vector
	template<typename Vector, typename PRNG>
	inline Vector& shuffle(Vector& v, PRNG& g) {
		return shuffle(v, g, square(v.size() - 1));
	}

}}

#endif
