var core__traits_8h =
[
    [ "theoretica::_internal::make_void< Args >", "structtheoretica_1_1__internal_1_1make__void.html", null ],
    [ "theoretica::is_real_type< Type >", "structtheoretica_1_1is__real__type.html", null ],
    [ "theoretica::is_real_type< real >", "structtheoretica_1_1is__real__type_3_01real_01_4.html", null ],
    [ "theoretica::is_orderable< Structure, typename >", "structtheoretica_1_1is__orderable.html", null ],
    [ "theoretica::is_orderable< Structure, _internal::void_t< decltype(std::declval< Structure >()< std::declval< Structure >())> >", "structtheoretica_1_1is__orderable_3_01_structure_00_01__internal_1_1void__t_3_01decltype_07std_12e209b403793e9b560712d8d8a4def95.html", null ],
    [ "theoretica::is_indexable< Structure, typename >", "structtheoretica_1_1is__indexable.html", null ],
    [ "theoretica::is_indexable< Structure, _internal::void_t< decltype(std::declval< Structure >()[0])> >", "structtheoretica_1_1is__indexable_3_01_structure_00_01__internal_1_1void__t_3_01decltype_07std_19d7f4fd42f60d1d5bc87491fe492c2a4.html", null ],
    [ "theoretica::is_iterable< Structure, typename >", "structtheoretica_1_1is__iterable.html", null ],
    [ "theoretica::is_iterable< Structure, _internal::void_t< decltype(std::declval< Structure >().begin())> >", "structtheoretica_1_1is__iterable_3_01_structure_00_01__internal_1_1void__t_3_01decltype_07std_1_134cacadc4237e7975e93632d0bd7c70.html", null ],
    [ "theoretica::is_vector< Structure, typename >", "structtheoretica_1_1is__vector.html", null ],
    [ "theoretica::is_vector< Structure, _internal::void_t< decltype(std::declval< Structure >()[0]), decltype(std::declval< Structure >().size())> >", "structtheoretica_1_1is__vector_3_01_structure_00_01__internal_1_1void__t_3_01decltype_07std_1_1deff424bfb078b2dba726f0fba11ce5f9.html", null ],
    [ "theoretica::is_matrix< Structure, typename >", "structtheoretica_1_1is__matrix.html", null ],
    [ "theoretica::is_matrix< Structure, _internal::void_t< decltype(std::declval< Structure >()(0, 0)), decltype(std::declval< Structure >().rows()), decltype(std::declval< Structure >().cols())> >", "structtheoretica_1_1is__matrix_3_01_structure_00_01__internal_1_1void__t_3_01decltype_07std_1_1d71853b5e69a5a4d7531f2d68fdf8bdec.html", null ],
    [ "theoretica::_internal::vector_element_or_void< Structure, typename >", "structtheoretica_1_1__internal_1_1vector__element__or__void.html", null ],
    [ "theoretica::_internal::vector_element_or_void< Structure, _internal::void_t< decltype(std::declval< Structure & >()[0])> >", "structtheoretica_1_1__internal_1_1vector__element__or__void_3_01_structure_00_01__internal_1_1vofa6d2fbbb140b6fff47e7c033156528f.html", null ],
    [ "theoretica::has_type_elements< Structure, Type >", "structtheoretica_1_1has__type__elements.html", null ],
    [ "theoretica::extract_func_args< Function(Args...)>", "structtheoretica_1_1extract__func__args_3_01_function_07_args_8_8_8_08_4.html", null ],
    [ "theoretica::_internal::get_first< Arg, Other >", "structtheoretica_1_1__internal_1_1get__first.html", null ],
    [ "theoretica::_internal::return_type_or_void< Function, T, typename >", "structtheoretica_1_1__internal_1_1return__type__or__void.html", null ],
    [ "theoretica::_internal::return_type_or_void< Function, T, _internal::void_t< decltype(std::declval< Function >()(T(0.0)))> >", "structtheoretica_1_1__internal_1_1return__type__or__void_3_01_function_00_01_t_00_01__internal_1269559a89b2061bef1e09b04d2db8427.html", null ],
    [ "theoretica::_internal::func_helper< T >", "structtheoretica_1_1__internal_1_1func__helper.html", null ],
    [ "theoretica::_internal::func_helper< ReturnType(Args...)>", "structtheoretica_1_1__internal_1_1func__helper_3_01_return_type_07_args_8_8_8_08_4.html", null ],
    [ "theoretica::_internal::func_helper< ReturnType(*)(Args...)>", "structtheoretica_1_1__internal_1_1func__helper_3_01_return_type_07_5_08_07_args_8_8_8_08_4.html", null ],
    [ "theoretica::_internal::func_helper< ReturnType(Class::*)(Args...) const >", "structtheoretica_1_1__internal_1_1func__helper_3_01_return_type_07_class_1_1_5_08_07_args_8_8_8_08_01const_01_4.html", null ]
];