var hierarchy =
[
    [ "theoretica::random::BasePrng< UIntType >", "structtheoretica_1_1random_1_1_base_prng.html", null ],
    [ "theoretica::random::BasePrng< uint64_t >", "structtheoretica_1_1random_1_1_base_prng.html", [
      [ "theoretica::random::SplitmixPrng", "structtheoretica_1_1random_1_1_splitmix_prng.html", null ],
      [ "theoretica::random::WyrandPrng", "structtheoretica_1_1random_1_1_wyrand_prng.html", null ],
      [ "theoretica::random::XoshiroPrng", "structtheoretica_1_1random_1_1_xoshiro_prng.html", null ]
    ] ],
    [ "theoretica::complex< Type >", "classtheoretica_1_1complex.html", null ],
    [ "theoretica::data_table", "classtheoretica_1_1data__table.html", null ],
    [ "theoretica::dual", "classtheoretica_1_1dual.html", null ],
    [ "theoretica::dual2", "classtheoretica_1_1dual2.html", null ],
    [ "theoretica::reprod::environment", "structtheoretica_1_1reprod_1_1environment.html", null ],
    [ "theoretica::io::hdf5_file", "classtheoretica_1_1io_1_1hdf5__file.html", null ],
    [ "theoretica::io::hdf5_handle", "structtheoretica_1_1io_1_1hdf5__handle.html", null ],
    [ "theoretica::io::hdf5_node", "structtheoretica_1_1io_1_1hdf5__node.html", null ],
    [ "theoretica::histogram", "classtheoretica_1_1histogram.html", null ],
    [ "theoretica::iter_result< Type >", "structtheoretica_1_1iter__result.html", null ],
    [ "theoretica::regression::linear_model", "structtheoretica_1_1regression_1_1linear__model.html", null ],
    [ "theoretica::mat< Type, N, K >", "classtheoretica_1_1mat.html", null ],
    [ "theoretica::mat< real, 2, 2 >", "classtheoretica_1_1mat.html", null ],
    [ "theoretica::mat< Type, 0, 0 >", "classtheoretica_1_1mat_3_01_type_00_010_00_010_01_4.html", null ],
    [ "theoretica::mat_iterator< Matrix, ReturnType >", "classtheoretica_1_1mat__iterator.html", null ],
    [ "theoretica::math_exception", "classtheoretica_1_1math__exception.html", null ],
    [ "theoretica::multidual< N >", "classtheoretica_1_1multidual.html", null ],
    [ "theoretica::ode::ode_solution_t< Vector >", "structtheoretica_1_1ode_1_1ode__solution__t.html", null ],
    [ "theoretica::random::PdfSampler< PRNG >", "structtheoretica_1_1random_1_1_pdf_sampler.html", null ],
    [ "theoretica::phasor< Type >", "classtheoretica_1_1phasor.html", null ],
    [ "theoretica::polynomial< Type >", "classtheoretica_1_1polynomial.html", null ],
    [ "theoretica::quat< Type >", "classtheoretica_1_1quat.html", null ],
    [ "theoretica::ratio< T1, T2 >", "classtheoretica_1_1ratio.html", null ],
    [ "theoretica::stats::RunningMoments2< Type >", "classtheoretica_1_1stats_1_1_running_moments2.html", null ],
    [ "theoretica::spline", "classtheoretica_1_1spline.html", null ],
    [ "theoretica::spline_node", "structtheoretica_1_1spline__node.html", null ],
    [ "theoretica::stoch_result< Type >", "structtheoretica_1_1stoch__result.html", null ],
    [ "theoretica::vec< Type, N >", "classtheoretica_1_1vec.html", null ],
    [ "theoretica::vec< real >", "classtheoretica_1_1vec.html", null ],
    [ "theoretica::vec< real, 0 >", "classtheoretica_1_1vec.html", null ],
    [ "theoretica::vec< vec< real > >", "classtheoretica_1_1vec.html", null ],
    [ "theoretica::vec_iterator< Vector, ReturnType >", "classtheoretica_1_1vec__iterator.html", null ],
    [ "theoretica::random::WeylSequencer", "structtheoretica_1_1random_1_1_weyl_sequencer.html", null ]
];