var hierarchy =
[
    [ "chebyshev::err::assert_result", "structchebyshev_1_1err_1_1assert__result.html", null ],
    [ "chebyshev::benchmark::benchmark_options< InputType >", "structchebyshev_1_1benchmark_1_1benchmark__options.html", null ],
    [ "chebyshev::benchmark::benchmark_result", "structchebyshev_1_1benchmark_1_1benchmark__result.html", null ],
    [ "chebyshev::benchmark::benchmark_state", "structchebyshev_1_1benchmark_1_1benchmark__state.html", null ],
    [ "theoretica::complex< Type >", "classtheoretica_1_1complex.html", null ],
    [ "theoretica::dual", "classtheoretica_1_1dual.html", null ],
    [ "theoretica::dual2", "classtheoretica_1_1dual2.html", null ],
    [ "chebyshev::prec::equation_options< T >", "structchebyshev_1_1prec_1_1equation__options.html", null ],
    [ "chebyshev::prec::equation_result", "structchebyshev_1_1prec_1_1equation__result.html", null ],
    [ "chebyshev::err::err_state", "structchebyshev_1_1err_1_1err__state.html", null ],
    [ "chebyshev::err::errno_result", "structchebyshev_1_1err_1_1errno__result.html", null ],
    [ "chebyshev::prec::estimate_options< R, Args >", "structchebyshev_1_1prec_1_1estimate__options.html", null ],
    [ "chebyshev::prec::estimate_result", "structchebyshev_1_1prec_1_1estimate__result.html", null ],
    [ "chebyshev::err::exception_result", "structchebyshev_1_1err_1_1exception__result.html", null ],
    [ "theoretica::extract_func_args< Function >", "structtheoretica_1_1extract__func__args.html", null ],
    [ "theoretica::extract_func_args< Function(Args...)>", "structtheoretica_1_1extract__func__args_3_01_function_07_args_8_8_8_08_4.html", null ],
    [ "std::false_type", null, [
      [ "theoretica::is_complex_type< T >", "structtheoretica_1_1is__complex__type.html", null ],
      [ "theoretica::is_dual2_type< Type >", "structtheoretica_1_1is__dual2__type.html", null ],
      [ "theoretica::is_dual_type< Type >", "structtheoretica_1_1is__dual__type.html", null ],
      [ "theoretica::is_indexable< Structure, typename >", "structtheoretica_1_1is__indexable.html", null ],
      [ "theoretica::is_iterable< Structure, typename >", "structtheoretica_1_1is__iterable.html", null ],
      [ "theoretica::is_matrix< Structure, typename >", "structtheoretica_1_1is__matrix.html", null ],
      [ "theoretica::is_multidual_type< Type >", "structtheoretica_1_1is__multidual__type.html", null ],
      [ "theoretica::is_orderable< Structure, typename >", "structtheoretica_1_1is__orderable.html", null ],
      [ "theoretica::is_vector< Structure, typename >", "structtheoretica_1_1is__vector.html", null ]
    ] ],
    [ "chebyshev::output::field_options", "structchebyshev_1_1output_1_1field__options.html", null ],
    [ "theoretica::histogram", "classtheoretica_1_1histogram.html", null ],
    [ "chebyshev::prec::interval", "structchebyshev_1_1prec_1_1interval.html", null ],
    [ "std::is_floating_point", null, [
      [ "theoretica::is_real_type< Type >", "structtheoretica_1_1is__real__type.html", null ]
    ] ],
    [ "std::is_same", null, [
      [ "theoretica::has_type_elements< Structure, Type >", "structtheoretica_1_1has__type__elements.html", null ]
    ] ],
    [ "theoretica::regression::linear_model", "structtheoretica_1_1regression_1_1linear__model.html", null ],
    [ "theoretica::_internal::make_void< Args >", "structtheoretica_1_1__internal_1_1make__void.html", null ],
    [ "theoretica::mat< Type, N, K >", "classtheoretica_1_1mat.html", null ],
    [ "theoretica::mat< real, 2, 2 >", "classtheoretica_1_1mat.html", null ],
    [ "theoretica::mat< Type, 0, 0 >", "classtheoretica_1_1mat_3_01_type_00_010_00_010_01_4.html", null ],
    [ "theoretica::mat_iterator< Matrix, ReturnType >", "classtheoretica_1_1mat__iterator.html", null ],
    [ "theoretica::multidual< N >", "classtheoretica_1_1multidual.html", null ],
    [ "theoretica::ode_state< N >", "structtheoretica_1_1ode__state.html", null ],
    [ "theoretica::ode_state< 1 >", "structtheoretica_1_1ode__state_3_011_01_4.html", null ],
    [ "chebyshev::output::output_state", "structchebyshev_1_1output_1_1output__state.html", null ],
    [ "theoretica::pdf_sampler", "structtheoretica_1_1pdf__sampler.html", null ],
    [ "theoretica::phasor< Type >", "classtheoretica_1_1phasor.html", null ],
    [ "theoretica::polynomial< Type >", "classtheoretica_1_1polynomial.html", null ],
    [ "chebyshev::prec::prec_state", "structchebyshev_1_1prec_1_1prec__state.html", null ],
    [ "theoretica::PRNG", "classtheoretica_1_1_p_r_n_g.html", null ],
    [ "theoretica::quat< Type >", "classtheoretica_1_1quat.html", null ],
    [ "chebyshev::random::random_state", "structchebyshev_1_1random_1_1random__state.html", null ],
    [ "theoretica::ratio< T1, T2 >", "classtheoretica_1_1ratio.html", null ],
    [ "theoretica::spline", "classtheoretica_1_1spline.html", null ],
    [ "theoretica::spline_node", "structtheoretica_1_1spline__node.html", null ],
    [ "chebyshev::benchmark::timer", "classchebyshev_1_1benchmark_1_1timer.html", null ],
    [ "std::true_type", null, [
      [ "theoretica::is_complex_type< complex< T > >", "structtheoretica_1_1is__complex__type_3_01complex_3_01_t_01_4_01_4.html", null ],
      [ "theoretica::is_dual2_type< dual2 >", "structtheoretica_1_1is__dual2__type_3_01dual2_01_4.html", null ],
      [ "theoretica::is_dual_type< dual >", "structtheoretica_1_1is__dual__type_3_01dual_01_4.html", null ],
      [ "theoretica::is_indexable< Structure, _internal::void_t< decltype(std::declval< Structure >()[0])> >", "structtheoretica_1_1is__indexable_3_01_structure_00_01__internal_1_1void__t_3_01decltype_07std_19d7f4fd42f60d1d5bc87491fe492c2a4.html", null ],
      [ "theoretica::is_iterable< Structure, _internal::void_t< decltype(std::declval< Structure >().begin())> >", "structtheoretica_1_1is__iterable_3_01_structure_00_01__internal_1_1void__t_3_01decltype_07std_1_134cacadc4237e7975e93632d0bd7c70.html", null ],
      [ "theoretica::is_matrix< Structure, _internal::void_t< decltype(std::declval< Structure >()(0, 0)), decltype(std::declval< Structure >().rows()), decltype(std::declval< Structure >().cols())> >", "structtheoretica_1_1is__matrix_3_01_structure_00_01__internal_1_1void__t_3_01decltype_07std_1_1d71853b5e69a5a4d7531f2d68fdf8bdec.html", null ],
      [ "theoretica::is_multidual_type< multidual< N > >", "structtheoretica_1_1is__multidual__type_3_01multidual_3_01_n_01_4_01_4.html", null ],
      [ "theoretica::is_orderable< Structure, _internal::void_t< decltype(std::declval< Structure >()< std::declval< Structure >())> >", "structtheoretica_1_1is__orderable_3_01_structure_00_01__internal_1_1void__t_3_01decltype_07std_12e209b403793e9b560712d8d8a4def95.html", null ],
      [ "theoretica::is_real_type< real >", "structtheoretica_1_1is__real__type_3_01real_01_4.html", null ],
      [ "theoretica::is_vector< Structure, _internal::void_t< decltype(std::declval< Structure >()[0]), decltype(std::declval< Structure >().size())> >", "structtheoretica_1_1is__vector_3_01_structure_00_01__internal_1_1void__t_3_01decltype_07std_1_1deff424bfb078b2dba726f0fba11ce5f9.html", null ]
    ] ],
    [ "theoretica::vec< Type, N >", "classtheoretica_1_1vec.html", null ],
    [ "theoretica::vec< real, 0 >", "classtheoretica_1_1vec.html", null ],
    [ "theoretica::vec< Type, 0 >", "classtheoretica_1_1vec_3_01_type_00_010_01_4.html", null ],
    [ "theoretica::vec_iterator< Vector, ReturnType >", "classtheoretica_1_1vec__iterator.html", null ],
    [ "theoretica::_internal::vector_element_or_void< Structure, typename >", "structtheoretica_1_1__internal_1_1vector__element__or__void.html", null ],
    [ "theoretica::_internal::vector_element_or_void< Structure, _internal::void_t< decltype(std::declval< Structure & >()[0])> >", "structtheoretica_1_1__internal_1_1vector__element__or__void_3_01_structure_00_01__internal_1_1vofa6d2fbbb140b6fff47e7c033156528f.html", null ]
];